if (WIN32)
    include(${CMAKE_CURRENT_SOURCE_DIR}/PlatformWin.cmake)
elseif (APPLE)
    include(${CMAKE_CURRENT_SOURCE_DIR}/PlatformMac.cmake)
else ()
    include(${CMAKE_CURRENT_SOURCE_DIR}/PlatformJSCOnly.cmake)
endif ()
